# Generated by Django 6.0.1 on 2026-01-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='规格型号(SKU)')),
                ('name', models.CharField(max_length=200, verbose_name='物料名称')),
                ('mnemonic', models.CharField(blank=True, max_length=100, verbose_name='助记码')),
                ('spec_details', models.TextField(blank=True, verbose_name='详细规格参数')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='产品图片')),
                ('incoming_qty', models.IntegerField(default=0, verbose_name='采购在途数量')),
                ('estimated_delivery', models.CharField(blank=True, max_length=100, verbose_name='预计交期')),
            ],
            options={
                'verbose_name': '产品基础信息',
                'verbose_name_plural': '产品基础信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(default='Guest', max_length=100, verbose_name='客户姓名')),
                ('guest_phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('guest_email', models.EmailField(blank=True, max_length=100, verbose_name='电子邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('status', models.CharField(choices=[('New', '新订单'), ('Done', '已完成')], default='New', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='下单客户(账号)')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100, verbose_name='目的仓库')),
                ('qty', models.IntegerField(default=0, verbose_name='补货数量')),
                ('arrival_date', models.DateField(verbose_name='预计到货日期')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '在途/补货管理',
                'verbose_name_plural': '在途/补货管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号码')),
                ('country_suffix', models.CharField(blank=True, help_text='例如填 TW，系统只显示SKU中包含 -TW 的商品', max_length=10, verbose_name='地区后缀代码')),
                ('allowed_warehouses', models.CharField(blank=True, default='ALL', help_text="填'ALL'看全部，或填具体仓库名用逗号隔开", max_length=500, verbose_name='可见仓库列表')),
                ('blocked_product_keywords', models.TextField(blank=True, help_text='包含这些字的商品，该客户看不见', verbose_name='屏蔽商品名称关键字')),
                ('recommended_products', models.ManyToManyField(blank=True, related_name='recommended_to_users', to='core.product', verbose_name='专属推荐商品')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('stock_org', models.CharField(blank=True, max_length=100, verbose_name='库存组织')),
                ('qty', models.IntegerField(default=0, verbose_name='库存数量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '库存明细',
                'verbose_name_plural': '库存明细',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
